---

- name: "Fail if non Debian based distro"
  fail: msg="Only Debian based distros are supported by this role"
  when: ansible_os_family != "Debian"

- name: "Make sure we're using systemd"
  assert:
    that:
      - ansible_service_mgr == "systemd"
